#%RAML 0.8
title: Hello RAML
baseUri: https://{bucketName}.s3.amazonaws.com
version: v1
description: |
  Show the full list of artists.
  Show the full list of albums.
  Show the list of artists by nationality.
  Show the list of albums by genre.
  Search for a song by title.
  Show a particular artist's albums collection.
  Show a particular album's songs list.
  Play a song (by specifying the song id).
  Enter new Artists, Albums and Songs (only authenticated users).
/songs:
  get:
  post:
  /{songId}:
    get:
    /file-content:
      get:
      post:
/artists:
  get:
  post:
  /{artistId}:
    get:
    /albums:
      get:
/albums:
  get:
  post:
  /{albumId}:
    get:
    /songs:
      get:
